

# This file was *autogenerated* from the file sum.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
sum=_sage_const_0 
x=int(input("Start: "))
y=int(input("End: "))
for i in range(x,y):
    p=input("give: ")
    i=var('i')
    sum=sum+p
print(sum)

